apiVersion: v1
items:
- apiVersion: config.openshift.io/v1
  kind: OAuth
  metadata:
    annotations:
      include.release.openshift.io/ibm-cloud-managed: "true"
      include.release.openshift.io/self-managed-high-availability: "true"
      include.release.openshift.io/single-node-developer: "true"
      release.openshift.io/create-only: "true"
    creationTimestamp: "2022-07-12T11:55:27Z"
    generation: 1
    name: cluster
    ownerReferences:
    - apiVersion: config.openshift.io/v1
      kind: ClusterVersion
      name: version
      uid: 1ca64482-ba72-4021-8ae2-cfc1140449a8
    resourceVersion: "1684"
    uid: b21d7582-8b97-464e-bff0-a7451cbc51de
  spec:
    identityProviders:
    - name: my_htpasswd_provider 
      mappingMethod: claim 
      type: HTPasswd
      htpasswd:
        fileData:
          name: htpass-secret 
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
